name: Run Cypress Tests

on:
  push:
    branches:
      - cypress1  # or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or any branch you want to trigger the workflow on

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'  # specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run --spec 'cypress/e2e/Test/firstTest.cy.js'
